"""Generate the working loon's motion files from the supplied artwork.

Every path is copied verbatim from assets/logos and assets/illustrations; a motion file adds
only clip regions, CSS animation, and a rule that stands the loon still under
prefers-reduced-motion. tests/test_motion.py regenerates the files and compares bytes.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INK, PAPER, EYE_RED = '#2b373d', '#F6F2E7', '#c30000'

# The loon's back is the checkered wedge below the line of the back (y = 436.39) and left of
# the lens's straight edge, (424.76, 413.51) to (265.93, 558.70). The divide sits 2.5 units
# inside the lens, and the back's clip reaches 1 unit above the line of the back, so the two
# copies overlap where both are ink and no seam shows at rest. The back pivots at the
# shoulder, where the two edges meet.
_SLOPE = (558.70 - 413.51) / (265.93 - 424.76)
_X0 = 424.76 + 2.5


def _x_at(y):
    return _X0 + (y - 413.51) / _SLOPE


_FLOOR = 413.51 - _X0 * _SLOPE
BACK = f'{_x_at(435.39):.2f},435.39 0,435.39 0,{_FLOOR:.2f}'
REST = f'0,0 800,0 800,900 0,900 0,{_FLOOR:.2f} {_x_at(436.39):.2f},436.39 0,436.39'
SHOULDER = f'{_x_at(436.39):.2f}px 436.39px'

REDUCED = '@media (prefers-reduced-motion: reduce) { * { animation: none !important; } }'
APPEAR = '@keyframes appear { from { opacity: 0; } to { opacity: 1; } }'
BEAT = ('@keyframes beat { 0%, 58%, 100% { transform: rotate(0deg); } 14%, 42% { transform: rotate(32deg); } '
        '28% { transform: rotate(6deg); } }')
RISE = ('@keyframes rise { 0%, 58%, 100% { transform: translateY(0); } 14%, 42% { transform: translateY(-10px); } '
        '28% { transform: translateY(-5px); } }')

# The dive, 5.4 s a cycle: rest, rear back, tip forward under the water line (y = 592, just
# under the breast), swim back unseen, surface, shake the back twice, rest. The ripples are
# drawn over the bird, so it slips behind them.
DIVE = [('0%, 8%', 0, 0, 0), ('14%', -6, -10, -8), ('24%', 12, 84, 22), ('32%', 40, 330, 40),
        ('33%, 56%', -80, 330, -10), ('66%', 0, 40, -6), ('72%', 0, -12, 0), ('78%, 100%', 0, 0, 0)]
SHAKE = [('0%, 76%', 0), ('80%', 30), ('85%', 4), ('90%', 30), ('96%, 100%', 0)]
SPLASH = [('0%, 22%', 1), ('30%', 1.14), ('42%, 64%', 1), ('72%', 1.1), ('82%, 100%', 1)]

WIDE = '140 270 490 440'          # the loon on its ripples, with room for the lifted back
SMALL = '123.88 180.39 512 512'   # the favicon's own crop


def _supplied():
    mark = (ROOT / 'assets/logos/loon-mark.svg').read_text()
    favicon = (ROOT / 'assets/logos/loon-favicon.svg').read_text()
    _frame, loon, ripple, ripple2 = re.findall(rf'<path fill="{INK}" d="([^"]+)"', mark)
    [small] = re.findall(rf'<path fill="{INK}" d="([^"]+)"', favicon)
    eye = re.search(r'<circle fill="#c30000" (cx="[^"]+" cy="[^"]+" r="[^"]+")', mark).group(1)
    assert eye in favicon
    return loon, ripple, ripple2, small, f'<circle fill="{EYE_RED}" {eye}/>'


def _svg(view_box, name, what, style, defs, body):
    width, height = view_box.split()[2:]
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view_box}" width="{width}" height="{height}">\n'
            f'  <!-- {name}: {what}\n'
            '       LoonSec design foundations, "The loon at work" in guide/brand.md. Generated by\n'
            '       tools/motion.py; the paths are the supplied artwork, unchanged. -->\n'
            '  <style>\n' + ''.join(f'    {line}\n' for line in style) + f'    {REDUCED}\n  </style>\n'
            f'  <defs>{defs}</defs>\n'
            f'  <g class="mark">\n{body}  </g>\n</svg>\n')


def _clips(extra=''):
    return (f'<clipPath id="back" clipPathUnits="userSpaceOnUse"><polygon points="{BACK}"/></clipPath>'
            f'<clipPath id="rest" clipPathUnits="userSpaceOnUse"><polygon points="{REST}"/></clipPath>{extra}')


def _bird(ink, loon, eye):
    return (f'<g class="bird"><path fill="{ink}" clip-path="url(#rest)" d="{loon}"/>{eye}'
            f'<g class="back"><path fill="{ink}" clip-path="url(#back)" d="{loon}"/></g></g>')


def _beating(extra=()):
    return ['.mark { animation: appear .2s ease-out .3s both; }',
            '.bird { transform-box: view-box; animation: rise 1.8s ease-in-out infinite; }',
            f'.back {{ transform-box: view-box; transform-origin: {SHOULDER}; animation: beat 1.8s ease-in-out infinite; }}',
            *extra, APPEAR, BEAT, RISE]


def _files():
    loon, ripple, ripple2, small, eye = _supplied()
    drift = ['.ripple { transform-box: view-box; animation: drift 3.6s ease-in-out infinite alternate; }',
             '.ripple.second { animation-delay: -1.8s; }',
             '@keyframes drift { from { transform: translateX(-8px); } to { transform: translateX(8px); } }']
    dive = [('.mark { animation: appear .2s ease-out .3s both; }'),
            '.bird { transform-box: view-box; transform-origin: 390px 520px; animation: dive 5.4s ease-in-out infinite; }',
            f'.back {{ transform-box: view-box; transform-origin: {SHOULDER}; animation: shake 5.4s ease-in-out infinite; }}',
            '.ripple { transform-box: view-box; transform-origin: 385px 630px; animation: splash 5.4s ease-in-out infinite; }',
            APPEAR,
            '@keyframes dive { ' + ' '.join(f'{k} {{ transform: translate({x}px, {y}px) rotate({a}deg); }}' for k, x, y, a in DIVE) + ' }',
            '@keyframes shake { ' + ' '.join(f'{k} {{ transform: rotate({a}deg); }}' for k, a in SHAKE) + ' }',
            '@keyframes splash { ' + ' '.join(f'{k} {{ transform: scaleX({s}); }}' for k, s in SPLASH) + ' }']
    for ink, suffix in ((INK, ''), (PAPER, '-reversed')):
        ripples = (f'    <path class="ripple" fill="{ink}" d="{ripple}"/>\n'
                   f'    <path class="ripple second" fill="{ink}" d="{ripple2}"/>\n')
        yield (f'loon-working{suffix}.svg', _svg(
            WIDE, f'loon-working{suffix}', 'the loon on its ripples, beating its back while work is in flight.',
            _beating(), _clips(), ripples + f'    {_bird(ink, loon, eye)}\n'))
        yield (f'loon-working-page{suffix}.svg', _svg(
            WIDE, f'loon-working-page{suffix}', 'the same loon for a whole page that waits; the ripples drift.',
            _beating(drift), _clips(), ripples + f'    {_bird(ink, loon, eye)}\n'))
        yield (f'loon-working-small{suffix}.svg', _svg(
            SMALL, f'loon-working-small{suffix}', "the simplified loon (the favicon's geometry) beating its back, 16-31 px.",
            _beating(), _clips(), f'    {_bird(ink, small, eye)}\n'))
        yield (f'loon-diving{suffix}.svg', _svg(
            WIDE, f'loon-diving{suffix}', 'the loon dives, swims unseen, surfaces and shakes its back: long work of unknown length.',
            dive, _clips('<clipPath id="above" clipPathUnits="userSpaceOnUse"><rect x="0" y="0" width="800" height="592"/></clipPath>'),
            f'    <g clip-path="url(#above)">{_bird(ink, loon, eye)}</g>\n' + ripples))
    yield ('lake-working.svg', _lake())


def _lake():
    scene = (ROOT / 'assets/illustrations/lake-scene.svg').read_text()
    style = ('<style>\n'
             '       .loon { animation: ride 3.2s ease-in-out infinite; }\n'
             '       .ripple { animation: swell 3.2s ease-in-out infinite; }\n'
             '       .ripple.r2 { animation-delay: -1.6s; }\n'
             '       @keyframes ride { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(-3px); } }\n'
             '       @keyframes swell { 0%, 100% { transform: translateX(-4px); } 50% { transform: translateX(4px); } }\n'
             f'       {REDUCED}\n'
             '     </style>\n     ')
    out = scene.replace('<defs>', style + '<defs>', 1)
    out = out.replace('traced from the actual mark -->\n       <g>', 'traced from the actual mark -->\n       <g class="loon">', 1)
    assert out.count('class="loon"') == 1, 'lake-scene.svg changed shape; update tools/motion.py'
    return ('<!-- lake-working: the lake illustration with the loon riding the swell, for onboarding and a first run.\n'
            '     LoonSec design foundations, "The loon at work" in guide/brand.md. Generated by tools/motion.py;\n'
            '     the paths are assets/illustrations/lake-scene.svg, unchanged. -->\n' + out)


def generate(out=ROOT / 'assets/motion'):
    out.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in _files():
        (out / name).write_text(text)
        written.append(out / name)
    return written


if __name__ == '__main__':
    for path in generate():
        print(path.relative_to(ROOT))
